### ISSUE TITLE
The job gets stuck on submitting results to the pushgateway in stage cluster

### ISSUE THREAD

**Issue by fridex** [thoth-station/cleanup-job#216]
The job prints the last line:

```

2019-11-04 19:20:44,283 [1] INFO     thoth.cleanup_job:215: Submitting metrics to Prometheus pushgateway 'pushgateway.xxx.redhat.com:80'
--
```

and does not terminate....

See stage cluster for more info.

**Comment by goern** [comment]
Is this still valid?

**Comment by fridex** [comment]
> Is this still valid?

Yes, but we do not experience this as an issue since https://github.com/thoth-station/cleanup-job/pull/224
